global:
  scrape_interval: 15s  # Frecuencia de recolección de métricas

scrape_configs:
  - job_name: "transacciones-api"  # Nombre del servicio a monitorear
    metrics_path: "/metrics"       # Ruta donde Prometheus encuentra las métricas
    static_configs:
      - targets: ["host.docker.internal:8001"]  # Para Docker en Windows/macOS
        